name: "infrastructure"

networks:
  qik_ai_cluster:
    external: true

services:
  postgres:
    extends:
      file: database/docker-postgres.yml
      service: postgres
    volumes:
      - ../.deploy/data/postgres:/var/lib/postgresql/data
    container_name: ${DATABASE_HOST}
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      qik_ai_cluster:
        aliases:
          - ${DATABASE_HOST}
  adminer:
    container_name: adminer
    extends:
      file: database/docker-postgres.yml
      service: adminer
    depends_on:
      - postgres
    ports:
      - ${DATABASE_UI_PORT}:8080
    networks:
      - qik_ai_cluster
