server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://victorialogs:9428/insert/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576
    timeout: 10s

scrape_configs:
  - job_name: "docker"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: project
      - source_labels: [__meta_docker_container_image]
        target_label: image

    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            timestamp: timestamp
            level: level
            tag: tag
            message: message
            context: context
      - labels:
          level:
          tag:
          service:
          container:
          project:
      - timestamp:
          source: timestamp
          format: RFC3339
